### ISSUE TITLE
Tachidesk is unable to load extensions in docker.

### ISSUE THREAD

**Issue by varoOP** [Suwayomi/docker-tachidesk#3]
The docker command I am using: `docker run  -p 4567:4567  -v /home/myusername/.local/share/Tachidesk:/./home/suwayomi/.local/share/Tachidesk ghcr.io/suwayomi/tachidesk`

The log that it writes:
```
20:10:38.916 [main] INFO  suwayomi.tachidesk.server.ServerSetup - Running Tachidesk v0.5.4 revision r995
20:10:39.496 [main] INFO  suwayomi.tachidesk.server.util.AppMutex - Mutex status is clear, Resuming startup.
Nov 07, 2021 8:10:39 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
20:10:40.353 [main] INFO  de.neonew.exposed.migrations.RunMigrations - Running migrations on database jdbc:h2:/home/suwayomi/.local/share/Tachidesk/database
20:10:41.053 [main] INFO  de.neonew.exposed.migrations.RunMigrations - Database version before migrations: 18
20:10:41.054 [main] INFO  de.neonew.exposed.migrations.RunMigrations - Migrations finished successfully
20:10:41.606 [main] ERROR dorkbox.systemTray.SystemTray - Cannot use the SystemTray in a headless environment
20:10:41.664 [main] INFO  suwayomi.tachidesk.server.util.WebUIManager - WebUI Static files exists and is the correct revision
20:10:41.665 [main] INFO  suwayomi.tachidesk.server.util.WebUIManager - Verifying WebUI Static files...
20:10:41.794 [main] INFO  suwayomi.tachidesk.server.util.WebUIManager - md5: 71a7f4ddd11bd88ca72e00d9de0ede67
20:10:41.795 [main] INFO  suwayomi.tachidesk.server.JavalinSetup - Serving webUI static files
20:10:41.837 [main] INFO  io.javalin.Javalin - Static file handler added: StaticFileConfig(hostedPath=/, directory=/home/suwayomi/.local/share/Tachidesk/webUI, location=EXTERNAL, precompress=false, aliasCheck=null, headers={Cache-Control=max-age=0}, skipFileFunction=(javax.servlet.http.HttpServletRequest) -> kotlin.Boolean). File system location: '/home/suwayomi/.local/share/Tachidesk/webUI'
20:10:41.878 [main] INFO  io.javalin.Javalin - 
       __                      __ _            __ __
      / /____ _ _   __ ____ _ / /(_)____      / // /
 __  / // __ `/| | / // __ `// // // __ \    / // /_
/ /_/ // /_/ / | |/ // /_/ // // // / / /   /__  __/
\____/ \__,_/  |___/ \__,_//_//_//_/ /_/      /_/

          https://javalin.io/documentation

20:10:41.879 [main] INFO  io.javalin.Javalin - Starting Javalin ...
20:10:41.892 [main] INFO  io.javalin.Javalin - You are running Javalin 4.0.0 (released September 13, 2021).
20:10:42.090 [main] INFO  io.javalin.Javalin - Listening on http://0.0.0.0:4567/
20:10:42.091 [main] INFO  io.javalin.Javalin - Javalin started in 213ms \o/
java.io.IOException: Current OS and desktop configuration does not support `browseURL`
        at dorkbox.util.Desktop.browseURL(Desktop.java:154)
        at dorkbox.util.Desktop.browseURL(Desktop.java:115)
        at suwayomi.tachidesk.server.util.Browser.openInBrowser(Browser.kt:30)
        at suwayomi.tachidesk.server.JavalinSetup.javalinSetup$lambda-2$lambda-1(JavalinSetup.kt:56)
        at io.javalin.core.event.EventManager.fireEvent(EventManager.kt:18)
        at io.javalin.Javalin.start(Javalin.java:175)
        at io.javalin.Javalin.start(Javalin.java:147)
        at io.javalin.Javalin.start(Javalin.java:133)
        at suwayomi.tachidesk.server.JavalinSetup.javalinSetup(JavalinSetup.kt:59)
        at suwayomi.tachidesk.MainKt.main(Main.kt:15)
        at suwayomi.tachidesk.MainKt.main(Main.kt)
20:10:49.248 [DefaultDispatcher-worker-1] ERROR suwayomi.tachidesk.server.JavalinSetup - IOException while handling the request
java.net.UnknownHostException: raw.githubusercontent.com: Try again
        at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:930)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1325)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1278)
        at java.net.InetAddress.getAllByName(InetAddress.java:1194)
        at java.net.InetAddress.getAllByName(InetAddress.java:1128)
        at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49)
        at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:164)
        at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:129)
        at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:17)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at suwayomi.tachidesk.manga.impl.extension.github.ExtensionGithubApi.getRepo(ExtensionGithubApi.kt:73)
        at suwayomi.tachidesk.manga.impl.extension.github.ExtensionGithubApi.findExtensions(ExtensionGithubApi.kt:48)
        at suwayomi.tachidesk.manga.impl.extension.ExtensionsList.getExtensionList(ExtensionsList.kt:40)
        at suwayomi.tachidesk.manga.controller.ExtensionController$list$1.invokeSuspend(ExtensionController.kt:23)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
I am running this on a headless server. My guess is that since browseURL is not supported it's causing issues?

**Comment by killmetohell** [comment]
i'm having the same problem how did you fix it?

**Comment by lbineau** [comment]
@killmetohell I did have the same issue, I've used `network: host` and for IP address to my host IP environement variable `BIND_IP: 192.168.X.X`. Probably not the cleanest but I have very limited knowledge with docker.
