### ISSUE TITLE
Socks5 proxy is not working with 127.0.0.1 or host.docker.internal

### ISSUE THREAD

**Issue by linonetwo** [Suwayomi/docker-tachidesk#60]
In https://github.com/Suwayomi/docker-tachidesk/issues/59 , I tried both one, and still getting 

```
13:02:56.240 [DefaultDispatcher-worker-1] �[1;31mERROR�[0;39m suwayomi.tachidesk.manga.impl.extension.github.ExtensionGithubApi - Failed to get extensions from GitHub
java.net.ConnectException: Failed to connect to raw.githubusercontent.com/0.0.0.0:443
	at okhttp3.internal.connection.ConnectPlan.connectSocket(ConnectPlan.kt:256)
	at okhttp3.internal.connection.ConnectPlan.connectTcp(ConnectPlan.kt:128)
	at okhttp3.internal.connection.FastFallbackExchangeFinder$launchTcpConnect$1.runOnce(FastFallbackExchangeFinder.kt:138)
```

in the log.

<img width="631" alt="截屏2023-10-12 21 51 12" src="https://github.com/Suwayomi/docker-tachidesk/assets/3746270/ac19f3af-765a-480f-88f3-0f867b19e655">

And it is hard to say if this config is really working.

**Comment by linonetwo** [comment]
Maybe socks5 is OK. `raw.githubusercontent.com` error is caused by DNS pollusion. Adding hosts to docker config solves this:

```
raw.githubusercontent.com:151.101.76.133
```

but I'm not sure if socks5 is working, because loading things in sources is very slow.

Adding a `export http_proxy=http://host.docker.internal:1080` into `D:/Tachidesk-Comic/proxy.sh` and bind volume to `/home/suwayomi/.local/share/Tachidesk` and modify CMD to

```sh


CMD | /bin/sh /home/suwayomi/startup/startup_script.sh /home/suwayomi/.local/share/Tachidesk/proxy.sh
```

seem to work.
