### ISSUE TITLE
[BUG] java.lang.NumberFormatException: For input string: "00 - time of day at which the automated backup should be triggered"

### ISSUE THREAD

**Issue by sgpublic** [Suwayomi/docker-tachidesk#92]
docker-compose.yaml:

```yaml
version: "3"
services:
  suwayomi:
    image: ghcr.io/suwayomi/tachidesk:v1.0.0
    restart: always
    volumes:
      - /mnt/core/app/suwayomi:/home/suwayomi/.local/share/Tachidesk
    env_file: stack.env
    ports:
      - 14567:4567
```

stack.env:

```
TZ=Asia/Shanghai
AUTO_DOWNLOAD_CHAPTERS=true
UPDATE_EXCLUDE_UNREAD=false
BACKUP_TIME=02:00
```

The logs is as follow:

```
        "app" : {
            "debug" : true,
            "packageName" : "eu.kanade.tachiyomi"
        },
        "files" : {
            "cacheDir" : "/home/suwayomi/.local/share/Tachidesk/android-compat/appdata/cache",
            "codeCacheDir" : "/home/suwayomi/.local/share/Tachidesk/android-compat/appdata/code_cache",
            "dataDir" : "/home/suwayomi/.local/share/Tachidesk/android-compat/appdata/data",
            "databasesDir" : "/home/suwayomi/.local/share/Tachidesk/android-compat/appdata/databases",
            "downloadCacheDir" : "/home/suwayomi/.local/share/Tachidesk/android-compat/extappdata/downloadCache",
            "externalCacheDirs" : [
                "/home/suwayomi/.local/share/Tachidesk/android-compat/extappdata/cache"
            ],
            "externalFilesDirs" : [
                "/home/suwayomi/.local/share/Tachidesk/android-compat/extappdata/files"
            ],
            "externalMediaDirs" : [
                "/home/suwayomi/.local/share/Tachidesk/android-compat/extappdata/media"
            ],
            "externalStorageDir" : "/home/suwayomi/.local/share/Tachidesk/android-compat/extappdata",
            "filesDir" : "/home/suwayomi/.local/share/Tachidesk/android-compat/appdata/files",
            "noBackupFilesDir" : "/home/suwayomi/.local/share/Tachidesk/android-compat/appdata/no_backup",
            "obbDirs" : [
                "/home/suwayomi/.local/share/Tachidesk/android-compat/extappdata/obb"
            ],
            "packageDir" : "/home/suwayomi/.local/share/Tachidesk/android-compat/android-compat/packages",
            "prefsDir" : "/home/suwayomi/.local/share/Tachidesk/android-compat/appdata/shared_prefs",
            "rootDir" : "/home/suwayomi/.local/share/Tachidesk/android-compat/appdata"
        },
        "system" : {
            "isDebuggable" : true

}
    },
    "androidcompat" : {
        "rootDir" : "/home/suwayomi/.local/share/Tachidesk/android-compat"
    },
    "server" : {
        "autoDownloadNewChapters" : true,
        "autoDownloadNewChaptersLimit" : 0,
        "backupInterval" : 1,
        "backupPath" : "",
        "backupTTL" : 14,
        "backupTime" : "02:00 - time of day at which the automated backup should be triggered",
        "basicAuthEnabled" : false,
        "basicAuthPassword" : "",
        "basicAuthUsername" : "",
        "debugLogsEnabled" : false,
        "downloadAsCbz" : false,
        "downloadsPath" : "",
        "electronPath" : "",
        "excludeCompleted" : true,
        "excludeEntryWithUnreadChapters" : true,
        "excludeNotStarted" : true,
        "excludeUnreadChapters" : false,
        "extensionRepos" : [],
        "flareSolverrEnabled" : false,
        "flareSolverrSessionName" : "suwayomi",
        "flareSolverrSessionTtl" : 15,
        "flareSolverrTimeout" : 60,
        "flareSolverrUrl" : "http://localhost:8191",
        "globalUpdateInterval" : 12,
        "gqlDebugLogsEnabled" : false,
        "initialOpenInBrowserEnabled" : false,
        "ip" : "0.0.0.0",
        "localSourcePath" : "",
        "maxSourcesInParallel" : 6,
        "port" : 4567,
        "socksProxyEnabled" : false,
        "socksProxyHost" : "",
        "socksProxyPassword" : "",
        "socksProxyPort" : "",
        "socksProxyUsername" : "",
        "socksProxyVersion" : 5,
        "systemTrayEnabled" : false,
        "updateMangas" : false,
        "webUIChannel" : "stable",
        "webUIEnabled" : true,
        "webUIFlavor" : "WebUI",
        "webUIInterface" : "browser",
        "webUIUpdateCheckInterval" : 23
    }
}
13:59:38.744 [main] DEBUG suwayomi.tachidesk.server.ServerSetup -- Data Root directory is set to: /home/suwayomi/.local/share/Tachidesk
13:59:38.995 [main] INFO suwayomi.tachidesk.server.util.AppMutex -- Mutex status is clear, Resuming startup.
13:59:39.343 [main] INFO suwayomi.tachidesk.server.database.DBManager -- Using h2 database version 1.4
13:59:39.534 [main] INFO de.neonew.exposed.migrations.RunMigrations -- Running migrations on database jdbc:h2:/home/suwayomi/.local/share/Tachidesk/database
13:59:39.912 [main] INFO de.neonew.exposed.migrations.RunMigrations -- Database version before migrations: 36
13:59:39.913 [main] INFO de.neonew.exposed.migrations.RunMigrations -- Migrations finished successfully
13:59:40.045 [main] INFO Migration -- Running migrations, previous version 1, target version 1
13:59:40.056 [DefaultDispatcher-worker-5] INFO suwayomi.tachidesk.server.ServerSetup -- Socks Proxy changed - enabled=false address=: , username=, password=[REDACTED]
13:59:40.146 [main] ERROR suwayomi.tachidesk.server.ServerSetup -- unhandled exception
java.lang.NumberFormatException: For input string: "00 - time of day at which the automated backup should be triggered"
	at java.base/java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.base/java.lang.Integer.parseInt(Unknown Source)
	at java.base/java.lang.Integer.parseInt(Unknown Source)
	at suwayomi.tachidesk.manga.impl.backup.proto.ProtoBackupExport.scheduleAutomatedBackupTask(ProtoBackupExport.kt:84)
	at suwayomi.tachidesk.server.ServerSetupKt.applicationSetup(ServerSetup.kt:295)
	at suwayomi.tachidesk.MainKt.main(Main.kt:14)
	at suwayomi.tachidesk.MainKt.main(Main.kt)
```

**Comment by sgpublic** [comment]
same as https://github.com/Suwayomi/Suwayomi-Server/issues/885, but I did not do any additional operations, did not manually modify the server.conf file, just started it directly.
